version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip ./sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:/sonar-scanner-5.0.1.3006-linux/bin/
      
  build:
    commands:
      - set -e
      - sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -X -Dsonar.login=0a931e8d333b2dd3797088b0f49320920fd6db6e -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=Ayush-NCI_SnapVibe -Dsonar.organization=ayush-nci -DgeneratePom=true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=Ayush-NCI_SnapVibe >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
