version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - echo "Installing dependencies"
      - pip install -r requirements.txt
  build:
    commands:
      - echo "Running tests"
      - python manage.py test
  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
  discard-paths: yes

cache:
  paths:
    - '/root/.cache/pip'
